### ISSUE TITLE
Fiverrr project

### ISSUE THREAD

**Issue by prathyushnallamothu** [Prajwal-Koirala/prajwalkoirala-com#1]
Hey please answer me please its a request. Y r u doing this ? Do you feel it correct ? How will you feel if you are cheated by anyone who skips paying you

**Comment by prathyushnallamothu** [comment]
Hey y dont you change your name as cheater

**Comment by 065rsh** [comment]
⚠⚠⚠⚠ He is a scammer!!

This guy is a cheater and doesn't pay for the work that others do for him, we should report his GitHub as well!!

**Comment by Prajwal-Koirala** [comment]
> ⚠⚠⚠⚠ He is a scammer!!
> 
> This guy is a cheater and doesn't pay for the work that others do for him, we should report his GitHub as well!!

You asked me for $68k  and said u were being held as a hostage in your city and coudent leave your city until you paid.

**Comment by 065rsh** [comment]
Is that why everyone is calling you a scammer? Is that why you have been banned from the Discord Flutter community?

**Comment by Prajwal-Koirala** [comment]
> Is that why everyone is calling you a scammer? Is that why you have been banned from the Discord Flutter community?

U know something, one of my friends went to india once right and he told me he took a cab from the airport to the hotel and it took them 4+ hours to get there, the hotel was 0.5 miles from the airport, the cab drivers just went around and round trying to rack up as much money as possible even though there was no work and when u said it took u 200 hours to write 2x pages than yeah I knew this was shady and didn't want to deal with it

**Comment by 065rsh** [comment]
![Uploading Screenshot_2021-02-03-20-59-56-01.jpg…]()

**Comment by 065rsh** [comment]
Here you go...

![Uploading Screenshot_2021-02-03-20-59-56-01.jpg…]()

**Comment by Prajwal-Koirala** [comment]
Can u not comment here thanks.

**Comment by ashishkhuraishy** [comment]
> > Is that why everyone is calling you a scammer? Is that why you have been banned from the Discord Flutter community?
> 
> U know something, one of my friends went to india once right and he told me he took a cab from the airport to the hotel and it took them 4+ hours to get there, the hotel was 0.5 miles from the airport, the cab drivers just went around and round trying to rack up as much money as possible even though there was no work and when u said it took u 200 hours to write 2x pages than yeah I knew this was shady and didn't want to deal with it

If indians are shady why choose them for your work. You owe me and my friend a good amount. When can you settle that? Or are you going to ignore us again just like you are doing on discord
